"""Corrigiendo campos de auditoría

Revision ID: 216d3b03cf32
Revises: c0d9a27339fd
Create Date: 2026-03-08 19:00:39.165058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216d3b03cf32'
down_revision: Union[str, Sequence[str], None] = 'c0d9a27339fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
