"""Apply softdelete to user table

Revision ID: 2608451eb3bb
Revises: fc7ce2dd01d5
Create Date: 2026-02-10 23:49:25.659668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2608451eb3bb'
down_revision: Union[str, Sequence[str], None] = 'fc7ce2dd01d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creación'))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualización'))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True, comment='ID del usuario que creó el registro'))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True, comment='ID del usuario que actualizó el registro'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###
