"""Added user table

Revision ID: 9e3ad71b6696
Revises: 
Create Date: 2026-01-14 04:43:15.006377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3ad71b6696'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Primer nombre del usuario'),
    sa.Column('second_name', sa.String(length=100), nullable=True, comment='Segundo nombre del usuario'),
    sa.Column('first_surname', sa.String(length=100), nullable=False, comment='Primer apellido del usuario'),
    sa.Column('second_surname', sa.String(length=100), nullable=True, comment='Segundo apellido del usuario'),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
