"""Corrigiendo campo de actualización de auditoría

Revision ID: d9fca39deef2
Revises: 216d3b03cf32
Create Date: 2026-03-08 19:04:14.909537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9fca39deef2'
down_revision: Union[str, Sequence[str], None] = '216d3b03cf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='Fecha de actualización')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='Fecha de actualización')
    # ### end Alembic commands ###
